version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vercel
    versions:
    - 21.2.3
    - 21.3.0
    - 21.3.1
    - 21.3.2
    - 22.0.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: firebase-admin
    versions:
    - 9.6.0
  - dependency-name: nanoid
    versions:
    - 3.1.21
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: ini
    versions:
    - 1.3.8
